### ISSUE TITLE
Epic 11: Deployment

### ISSUE THREAD

**Issue by Comfort-Twala** [Comfort-Twala/Profile#11]
- [ ]  Choose a hosting platform (e.g., Vercel, Netlify)
- [ ]  Set up deployment process (consider CI/CD)
- [ ]  Configure custom domain
- [ ]  Ensure HTTPS is enabled
- [ ]  Set up environment variables for production
