### ISSUE TITLE
Epic: Decap CMS Integration for Project Management

### ISSUE THREAD

**Issue by Comfort-Twala** [Comfort-Twala/Profile#15]
- [ ]  Set up Decap CMS
- [ ]  Install Decap CMS package
- [ ]  Create configuration file (config.yml) for Decap CMS
- [ ]  Set up authentication (e.g., GitHub OAuth)
- [ ]  Configure Decap CMS for project management
- [ ]  Define collection for projects in config.yml
- [ ]  Set up fields for project title, description, technologies used, images, etc.
- [ ]  Create custom widgets for case study sections (challenge, solution, results) if needed
- [ ]  Integrate Decap CMS with Next.js
- [ ]  Set up admin route for CMS access (/admin)
- [ ]  Configure Decap CMS to work with your Git repository
- [ ]  Implement data fetching from local markdown files
- [ ]  Use getStaticProps and getStaticPaths for SSG of project pages
- [ ]  Implement markdown parsing (e.g., using remark or gray-matter)
- [ ]  Set up preview functionality for draft projects
- [ ]  Create preview templates for projects
- [ ]  Implement preview API route in Next.js
- [ ]  Configure webhooks to trigger rebuilds when content is updated
- [ ]  Set up webhook endpoint in deployment platform (e.g., Vercel)
- [ ]  Configure Decap CMS to call webhook on content changes
- [ ]  Create documentation for updating projects via Decap CMS
