### ISSUE TITLE
Epic 2: Core Structure and Styling

### ISSUE THREAD

**Issue by Comfort-Twala** [Comfort-Twala/Profile#2]
- [x]  Set up basic Next.js pages structure
- [x]  Implement layout component with Aceternity UI
- [x]  Set up global styles and theme
- [x]  Ensure responsive design using Aceternity UI components
- [x]  Implement navigation menu using Aceternity UI components
- [x] #20
- [ ]  Nav Dock Icons
