### ISSUE TITLE
Epic 3: About Me Section

### ISSUE THREAD

**Issue by Comfort-Twala** [Comfort-Twala/Profile#3]
- [x]  Create About Me page component
- [x]  Write personal bio
- [x]  Add professional photo (using Aceternity UI image component if applicable)
- [x]  #5 
- [ ] #23

**Comment by Comfort-Twala** [comment]
CV still to be made, but button already implemented and ready
