### ISSUE TITLE
Epic 4: Projects Showcase

### ISSUE THREAD

**Issue by Comfort-Twala** [Comfort-Twala/Profile#4]
- [ ]  Select top projects to feature
- [ ]  Write project descriptions and outcomes
- [ ]  Create project case study template as a reusable component
- [ ]  Implement project gallery/grid using Aceternity UI components
- [ ]  Add screenshots or demos for each project
- [ ]  Implement dynamic routing for individual project pages
