### ISSUE TITLE
Epic 6: Work Experience Section

### ISSUE THREAD

**Issue by Comfort-Twala** [Comfort-Twala/Profile#6]
- [x]  Create Work Experience page or section component
- [x]  List relevant work experiences
- [ ]  Write concise job descriptions
- [ ]  Highlight key achievements in each role
- [x]  Use Aceternity UI components for layout and styling

**Comment by Comfort-Twala** [comment]
Data to be updated, Frontend at satisfactory level
